import jsPDF from 'jspdf';

export interface PDFExportOptions {
  callId: string;
  customerName: string;
  salesRep: string;
  callDate: string;
  duration: number;
  sentiment: string;
  content: string;
  format: string;
}

export function generateCallPDF(options: PDFExportOptions): Blob {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);
  let yPosition = margin;

  // Helper function to add wrapped text
  const addWrappedText = (text: string, x: number, y: number, maxWidth: number, lineHeight: number = 5): number => {
    const lines = pdf.splitTextToSize(text, maxWidth);
    lines.forEach((line: string) => {
      if (y > pageHeight - margin) {
        pdf.addPage();
        y = margin;
      }
      pdf.text(line, x, y);
      y += lineHeight;
    });
    return y;
  };

  // Add header with gradient effect (simulated with rectangles)
  pdf.setFillColor(139, 92, 246); // Purple
  pdf.rect(0, 0, pageWidth, 40, 'F');

  // Add title
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(20);
  pdf.text('Call Summary Report', margin, 25);

  pdf.setTextColor(0, 0, 0);
  yPosition = 50;

  // Add call metadata box
  pdf.setDrawColor(139, 92, 246);
  pdf.setLineWidth(0.5);
  pdf.rect(margin, yPosition, contentWidth, 45, 'S');

  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');

  // Left column
  pdf.text('Customer:', margin + 5, yPosition + 10);
  pdf.text('Sales Rep:', margin + 5, yPosition + 18);
  pdf.text('Date:', margin + 5, yPosition + 26);

  // Right column
  pdf.text('Duration:', margin + contentWidth/2, yPosition + 10);
  pdf.text('Sentiment:', margin + contentWidth/2, yPosition + 18);
  pdf.text('Format:', margin + contentWidth/2, yPosition + 26);

  // Add values
  pdf.setFont('helvetica', 'normal');
  pdf.text(options.customerName || 'Unknown', margin + 25, yPosition + 10);
  pdf.text(options.salesRep || 'Unknown', margin + 25, yPosition + 18);
  pdf.text(options.callDate, margin + 25, yPosition + 26);

  pdf.text(`${options.duration} minutes`, margin + contentWidth/2 + 25, yPosition + 10);

  // Add sentiment with color
  const sentimentColor =
    options.sentiment === 'positive' ? [0, 128, 0] :
    options.sentiment === 'negative' ? [255, 0, 0] :
    [128, 128, 128];

  pdf.setTextColor(...sentimentColor as [number, number, number]);
  pdf.text(options.sentiment || 'neutral', margin + contentWidth/2 + 25, yPosition + 18);
  pdf.setTextColor(0, 0, 0);

  pdf.text(options.format.toUpperCase(), margin + contentWidth/2 + 25, yPosition + 26);

  yPosition += 55;

  // Add separator line
  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.2);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Add content title
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Extracted Data & Insights', margin, yPosition);
  yPosition += 10;

  // Add main content
  pdf.setFontSize(9);
  pdf.setFont('courier', 'normal');

  // Process content line by line
  const contentLines = options.content.split('\n');

  contentLines.forEach(line => {
    // Check if we need a new page
    if (yPosition > pageHeight - margin - 10) {
      pdf.addPage();
      yPosition = margin;
    }

    // Handle special formatting
    if (line.startsWith('━')) {
      // Draw a line for separators
      pdf.setDrawColor(200, 200, 200);
      pdf.line(margin, yPosition - 2, pageWidth - margin, yPosition - 2);
      yPosition += 5;
    } else if (line.startsWith('🎯') || line.startsWith('📊') || line.startsWith('💡')) {
      // Section headers - make them bold
      pdf.setFont('courier', 'bold');
      yPosition = addWrappedText(line, margin, yPosition, contentWidth, 5);
      pdf.setFont('courier', 'normal');
    } else if (line.trim() === '') {
      // Empty line - add small spacing
      yPosition += 3;
    } else {
      // Regular content
      yPosition = addWrappedText(line, margin, yPosition, contentWidth, 4);
    }
  });

  // Add footer on last page
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);

    // Add page numbers
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2 - 15,
      pageHeight - 10
    );

    // Add generated by text
    pdf.text(
      `Generated by SynQall - ${new Date().toLocaleDateString()}`,
      margin,
      pageHeight - 10
    );
  }

  // Return as Blob
  return pdf.output('blob');
}

export function downloadPDF(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}