#!/bin/bash

echo "========================================="
echo "DEEP MEMORY INVESTIGATION SCRIPT"
echo "========================================="
echo ""
echo "Run these commands on your VPS to investigate high memory usage:"
echo ""

echo "# 1. CHECK ACTUAL MEMORY vs CACHE"
echo "# ================================"
echo "free -h"
echo "# Look at 'buff/cache' column - Linux uses free RAM for caching"
echo ""

echo "# 2. DETAILED MEMORY BREAKDOWN"
echo "# ============================"
echo "cat /proc/meminfo | grep -E 'MemTotal|MemFree|MemAvailable|Buffers|Cached|Slab|SReclaimable|SUnreclaim'"
echo "# This shows exactly what's using memory"
echo ""

echo "# 3. CHECK SLAB MEMORY (Kernel Cache)"
echo "# ==================================="
echo "slabtop -o -s c | head -20"
echo "# or if slabtop not available:"
echo "cat /proc/slabinfo | head -20"
echo ""

echo "# 4. CHECK FOR MEMORY LEAKS IN PROCESSES"
echo "# ======================================"
echo "ps aux --sort=-rss | head -30"
echo "# Look for any process using unexpected memory"
echo ""

echo "# 5. CHECK SYSTEMD SERVICES MEMORY"
echo "# ================================"
echo "systemctl status | grep -E 'Memory:'"
echo "# or more detailed:"
echo "systemd-cgtop -m"
echo ""

echo "# 6. CHECK LOG FILE SIZES"
echo "# ======================="
echo "du -sh /var/log/* 2>/dev/null | sort -rh | head -20"
echo "journalctl --disk-usage"
echo "# Large logs can consume memory"
echo ""

echo "# 7. CHECK SHARED MEMORY"
echo "# ====================="
echo "ipcs -m"
echo "df -h /dev/shm"
echo "# PostgreSQL and other apps use shared memory"
echo ""

echo "# 8. CHECK POSTGRESQL MEMORY"
echo "# =========================="
echo "sudo -u postgres psql -c \"SHOW shared_buffers;\""
echo "sudo -u postgres psql -c \"SHOW effective_cache_size;\""
echo "sudo -u postgres psql -c \"SHOW work_mem;\""
echo "# PostgreSQL might be configured to use lots of memory"
echo ""

echo "# 9. CHECK FOR ZOMBIE PROCESSES"
echo "# ============================"
echo "ps aux | grep -E 'defunct|<zombie>'"
echo "# Zombie processes can hold memory"
echo ""

echo "# 10. CHECK TMPFS AND RAMDISK"
echo "# ==========================="
echo "df -h | grep -E 'tmpfs|ramfs'"
echo "mount | grep -E 'tmpfs|ramfs'"
echo "# Some directories might be mounted in RAM"
echo ""

echo "# 11. CHECK DOCKER/CONTAINERS (if any)"
echo "# ===================================="
echo "docker ps -a 2>/dev/null"
echo "docker stats --no-stream 2>/dev/null"
echo "# Containers can use significant memory"
echo ""

echo "# 12. DETAILED PROCESS MEMORY MAP"
echo "# ==============================="
echo "# For the top memory user (replace PID):"
echo "pmap -x [PID] | tail -5"
echo "# Shows memory breakdown of a specific process"
echo ""

echo "# 13. CHECK KERNEL MEMORY PARAMETERS"
echo "# =================================="
echo "sysctl vm.swappiness"
echo "sysctl vm.vfs_cache_pressure"
echo "sysctl vm.min_free_kbytes"
echo "# These control memory behavior"
echo ""

echo "# 14. MEMORY PRESSURE CHECK"
echo "# ========================"
echo "cat /proc/pressure/memory"
echo "# Shows if system is under memory pressure"
echo ""

echo "# 15. CLEAR CACHES (SAFELY)"
echo "# ========================"
echo "# To free up cache memory (safe, but temporary):"
echo "sync"
echo "echo 1 > /proc/sys/vm/drop_caches  # Clear PageCache only"
echo "# or"
echo "echo 2 > /proc/sys/vm/drop_caches  # Clear dentries and inodes"
echo "# or"
echo "echo 3 > /proc/sys/vm/drop_caches  # Clear all caches"
echo "# Then check memory again:"
echo "free -h"
echo ""

echo "========================================="
echo "LIKELY CULPRITS FOR HIGH MEMORY USAGE:"
echo "========================================="
echo ""
echo "1. BUFFER/CACHE (Most Likely)"
echo "   - Linux aggressively caches files in RAM"
echo "   - This is NORMAL and good for performance"
echo "   - Shows as 'used' but is available when needed"
echo "   - Check 'available' column, not 'free'"
echo ""
echo "2. POSTGRESQL CONFIGURATION"
echo "   - Default shared_buffers might be too high"
echo "   - Check: /etc/postgresql/*/main/postgresql.conf"
echo "   - Recommended: 25% of RAM for dedicated DB server"
echo "   - For mixed use: 10-15% of RAM"
echo ""
echo "3. SYSTEMD JOURNAL"
echo "   - Can grow very large"
echo "   - Check: journalctl --disk-usage"
echo "   - Clean: journalctl --vacuum-time=7d"
echo ""
echo "4. TMPFS MOUNTS"
echo "   - /tmp or /var/tmp might be in RAM"
echo "   - Check: df -h | grep tmpfs"
echo ""
echo "5. KERNEL SLAB CACHE"
echo "   - Kernel's internal cache"
echo "   - Check: slabtop or /proc/slabinfo"
echo ""

echo "========================================="
echo "QUICK FIX COMMANDS:"
echo "========================================="
echo ""
echo "# 1. Clear system caches (temporary but immediate):"
echo "sync && echo 3 > /proc/sys/vm/drop_caches"
echo ""
echo "# 2. Clean journal logs:"
echo "journalctl --vacuum-time=7d"
echo ""
echo "# 3. Clean apt cache:"
echo "apt-get clean"
echo ""
echo "# 4. Clean old logs:"
echo "find /var/log -type f -name '*.log' -mtime +30 -delete"
echo ""
echo "# 5. Restart services to release memory:"
echo "systemctl restart nginx"
echo "systemctl restart postgresql"
echo "pm2 restart all"
echo ""

echo "========================================="
echo "IMPORTANT NOTES:"
echo "========================================="
echo ""
echo "1. High buffer/cache is NORMAL in Linux"
echo "2. Look at 'available' memory, not 'free'"
echo "3. The system will release cache when needed"
echo "4. Your 8.3GB 'used' might include 5-6GB of cache"
echo "5. Actual application usage might be only 2-3GB"
echo ""
echo "Run these commands and share the output!"