#!/bin/bash

echo "=================================="
echo "FIND THE MISSING 6GB OF MEMORY"
echo "=================================="
echo ""
echo "Run these commands on your VPS:"
echo ""

echo "# 1. CHECK SLAB (KERNEL) MEMORY"
echo "# =============================="
echo "cat /proc/meminfo | grep -E 'Slab:|SReclaimable:|SUnreclaim:'"
echo "# Slab is kernel cache - can be very large"
echo ""

echo "# 2. CHECK ALL MEMORY CATEGORIES"
echo "# ==============================="
echo "cat /proc/meminfo | head -20"
echo "# Shows complete memory breakdown"
echo ""

echo "# 3. CHECK PAGE TABLES"
echo "# ===================="
echo "cat /proc/meminfo | grep PageTables"
echo "# Can be large with many processes"
echo ""

echo "# 4. CHECK ANONYMOUS MEMORY"
echo "# ========================"
echo "cat /proc/meminfo | grep -E 'AnonPages|AnonHugePages'"
echo "# Memory not backed by files"
echo ""

echo "# 5. DETAILED SYSTEM MEMORY"
echo "# ========================"
echo "smem -t -k -s swap | tail -20"
echo "# If smem not installed: apt-get install smem"
echo "# Shows actual memory usage per process"
echo ""

echo "# 6. CHECK MEMORY BY CGROUP"
echo "# ========================"
echo "systemd-cgtop -m"
echo "# Shows memory per service group"
echo ""

echo "# 7. CHECK HUGEPAGES"
echo "# =================="
echo "cat /proc/meminfo | grep -i huge"
echo "# HugePages can reserve large amounts"
echo ""

echo "# 8. CHECK VMALLOC USAGE"
echo "# ====================="
echo "cat /proc/vmallocinfo | awk '{total+=$2} END {print total/1024/1024 \" MB\"}'
echo "# Kernel virtual memory allocations"
echo ""

echo "# 9. MEMORY BY USER"
echo "# ================"
echo "ps aux | awk '{arr[$1]+=$6} END {for (i in arr) {print i,arr[i]/1024 \" MB\"}}' | sort -nk2 -r"
echo "# Shows memory per user"
echo ""

echo "# 10. CHECK FOR MEMORY LEAKS"
echo "# ========================="
echo "dmesg | grep -i 'out of memory'"
echo "dmesg | grep -i 'oom-killer'"
echo "# Check if OOM killer has been active"
echo ""

echo "=================================="
echo "MOST LIKELY EXPLANATIONS:"
echo "=================================="
echo ""
echo "1. KERNEL SLAB CACHE (Most Common)"
echo "   - Used for filesystem metadata"
echo "   - Can grow very large"
echo "   - Check: cat /proc/meminfo | grep Slab"
echo ""
echo "2. ANONYMOUS PAGES"
echo "   - Process memory not in cache"
echo "   - Check: cat /proc/meminfo | grep AnonPages"
echo ""
echo "3. MEMORY FRAGMENTATION"
echo "   - Memory allocated but not efficiently used"
echo "   - Common on long-running servers"
echo ""
echo "4. KERNEL MODULES"
echo "   - Drivers and kernel extensions"
echo "   - Check: lsmod | awk '{total+=$2} END {print total/1024 \" MB\"}'
echo ""

echo "=================================="
echo "TO FREE MEMORY IMMEDIATELY:"
echo "=================================="
echo ""
echo "# 1. Drop all caches (safe, temporary):"
echo "sync && echo 3 > /proc/sys/vm/drop_caches && free -h"
echo ""
echo "# 2. Clear systemd journal:"
echo "journalctl --vacuum-time=3d"
echo ""
echo "# 3. Restart PM2 processes:"
echo "pm2 restart all"
echo ""
echo "# 4. If still high, consider reboot:"
echo "# (Only if you can afford downtime)"
echo "# reboot"
echo ""